name: Advanced AI Model Performance Validation

on:
  schedule:
    - cron: '0 6 * * 1'  # Run weekly on Monday at 6 AM
  workflow_dispatch:  # Allow manual trigger
  pull_request:
    branches: [ main ]

jobs:
  advanced-model-benchmarking:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Advanced Model Benchmarking
      env:
        NVIDIA_API_KEY: ${{ secrets.NVIDIA_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      run: |
        cd tests
        python advanced_benchmarking.py
    
    - name: Upload Performance Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: model-performance-reports
        path: |
          reports/comprehensive_benchmark_report.json
          reports/model_performance.db
          reports/*.html
        retention-days: 30
    
    - name: Notify Performance Insights
      uses: 8398a7/action-slack@v3
      if: always()
      with:
        status: ${{ job.status }}
        text: |
          AI Model Performance Benchmark Completed! 
          Reports Generated: 
          - Comprehensive JSON Report
          - SQLite Performance Database
          - Interactive Visualizations
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}

